services:
  - type: web
    name: philip-morris-vehicle-tracking
    env: node
    plan: free
    buildCommand: cd client && npm install && npm run build && cd .. && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: philip-morris-vehicle-tracking
          property: port
